# Generated by Django 5.0.2 on 2025-08-04 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='etat',
        ),
        migrations.AddField(
            model_name='client',
            name='status',
            field=models.CharField(blank=True, choices=[('active', 'active'), ('inactive', 'inactive')], default='active', max_length=50, null=True),
        ),
    ]
