# Generated by Django 4.2.23 on 2025-08-16 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AlerteRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=20)),
                ('designation', models.CharField(max_length=100)),
                ('type', models.CharField(max_length=50)),
                ('intervalle_min', models.FloatField()),
                ('intervalle_max', models.FloatField()),
                ('date_debut', models.DateField()),
                ('date_fin', models.DateField()),
                ('heure_debut', models.TimeField()),
                ('heure_fin', models.TimeField()),
                ('frequence', models.CharField(max_length=50)),
                ('nb_notifs_jour', models.IntegerField()),
                ('message', models.TextField()),
                ('via_sms', models.BooleanField(default=False)),
                ('via_email', models.BooleanField(default=False)),
                ('tel_notif', models.CharField(blank=True, max_length=20, null=True)),
                ('email_notif', models.EmailField(blank=True, max_length=254, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='AlertLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nbr_email', models.IntegerField(default=0)),
                ('nbr_sms', models.IntegerField(default=0)),
                ('date_heure', models.DateTimeField()),
            ],
        ),
    ]
