# Generated by Django 5.0.2 on 2025-08-11 14:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alerterule',
            name='capture_site',
        ),
        migrations.RemoveField(
            model_name='alertlog',
            name='capture_site',
        ),
    ]
