# Generated by Django 4.2.23 on 2025-08-16 17:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('alerts', '0001_initial'),
        ('machines', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='alertlog',
            name='capture_machine',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='machines.capturemachine'),
        ),
        migrations.AddField(
            model_name='alerterule',
            name='capture_machine',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='machines.capturemachine'),
        ),
    ]
