# Generated by Django 4.2.23 on 2025-08-16 17:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('captures', '0001_initial'),
        ('machines', '0001_initial'),
        ('sites', '0002_alter_site_etat'),
    ]

    operations = [
        migrations.CreateModel(
            name='RapportPlanification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_rapport', models.CharField(max_length=100)),
                ('destinataire', models.CharField(max_length=255)),
                ('email_dest', models.EmailField(max_length=254)),
                ('type_rapport', models.CharField(max_length=50)),
                ('periodicite', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date_dernier_envoi', models.DateField()),
                ('heur_envoi', models.TimeField()),
                ('etat', models.CharField(max_length=20)),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sites.site')),
            ],
        ),
        migrations.CreateModel(
            name='RapportJournalier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_debut', models.DateField()),
                ('date_fin', models.DateField()),
                ('horaire_matin', models.TimeField()),
                ('horaire_midi', models.TimeField()),
                ('horaire_soire', models.TimeField()),
                ('machine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='machines.machine')),
                ('parametre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='captures.typeparametre')),
                ('rapport_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reports.rapportplanification')),
            ],
        ),
        migrations.CreateModel(
            name='RapportHistoriqueMesure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_debut', models.DateField()),
                ('date_fin', models.DateField()),
                ('heur_debut', models.TimeField()),
                ('heur_fin', models.TimeField()),
                ('frequence', models.DecimalField(decimal_places=2, max_digits=10)),
                ('machine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='machines.machine')),
                ('rapport_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reports.rapportplanification')),
            ],
        ),
        migrations.CreateModel(
            name='RapportAnalyseGraphique',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('heur_debut', models.TimeField()),
                ('heur_fin', models.TimeField()),
                ('capture_machine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='machines.capturemachine')),
                ('machine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='machines.machine')),
                ('rapport_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reports.rapportplanification')),
            ],
        ),
        migrations.CreateModel(
            name='LogRapport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_envoi', models.DateField()),
                ('heure_envoi', models.TimeField()),
                ('etat_envoi', models.CharField(max_length=20)),
                ('rapport_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reports.rapportplanification')),
            ],
        ),
    ]
