# Generated by Django 5.0.2 on 2025-08-04 18:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rapportplanification',
            old_name='etat',
            new_name='status',
        ),
    ]
