# Generated by Django 4.2.23 on 2025-08-02 03:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sites', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CaptureRFID',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_serie', models.CharField(max_length=100)),
                ('status', models.CharField(max_length=20)),
                ('date_install', models.DateField()),
                ('date_dernier_serveillance', models.DateField()),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rfid_captures', to='sites.site')),
            ],
        ),
        migrations.CreateModel(
            name='CaptureSite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_serie', models.CharField(max_length=100, unique=True)),
                ('status', models.CharField(max_length=20)),
                ('date_install', models.DateField()),
                ('date_dernier_serveillance', models.DateField()),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='captures', to='sites.site')),
            ],
        ),
        migrations.CreateModel(
            name='TypeParametre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50)),
                ('unite', models.CharField(max_length=20)),
                ('valeur_max', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SiteParametre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valeur', models.FloatField()),
                ('date_heure', models.DateTimeField()),
                ('capture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parametres', to='captures.capturesite')),
                ('parametre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='captures.typeparametre')),
            ],
        ),
        migrations.CreateModel(
            name='ObjectTracking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categorie', models.CharField(max_length=50)),
                ('dernier_update', models.DateTimeField()),
                ('etat', models.CharField(max_length=20)),
                ('latitude_depart', models.FloatField(blank=True, null=True)),
                ('longitude_depart', models.FloatField(blank=True, null=True)),
                ('latitude_actuel', models.FloatField(blank=True, null=True)),
                ('longitude_actuel', models.FloatField(blank=True, null=True)),
                ('latitude_dest', models.FloatField(blank=True, null=True)),
                ('longitude_dest', models.FloatField(blank=True, null=True)),
                ('capture_rfid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='object_trackings', to='captures.capturerfid')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='object_trackings', to='sites.site')),
            ],
        ),
        migrations.CreateModel(
            name='MesureTracking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_passage', models.DateField()),
                ('lieu', models.CharField(max_length=255)),
                ('heure', models.TimeField()),
                ('duree_passage', models.DurationField()),
                ('object_tracking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mesures', to='captures.objecttracking')),
            ],
        ),
    ]
