# Generated by Django 4.2.23 on 2025-08-16 17:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sites', '0002_alter_site_etat'),
    ]

    operations = [
        migrations.CreateModel(
            name='CaptureSite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_serie', models.CharField(max_length=100, unique=True)),
                ('status', models.CharField(choices=[('active', 'active'), ('inactive', 'inactive')], default='active', max_length=20)),
                ('date_install', models.DateField()),
                ('date_dernier_serveillance', models.DateField(blank=True, null=True)),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='captures', to='sites.site')),
            ],
        ),
        migrations.CreateModel(
            name='PathTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('source', models.CharField(max_length=100)),
                ('destination', models.CharField(max_length=100)),
                ('latitude_src', models.FloatField()),
                ('longitude_src', models.FloatField()),
                ('latitude_dest', models.FloatField()),
                ('longitude_dest', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='TrackingPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_lieu', models.CharField(max_length=100)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='TypeParametre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50)),
                ('unite', models.CharField(max_length=20)),
                ('valeur_max', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('capture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parametres', to='captures.capturesite')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parametre', to='sites.site')),
            ],
        ),
        migrations.CreateModel(
            name='TagRfid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_serie', models.CharField(max_length=100, unique=True)),
                ('status', models.CharField(choices=[('active', 'active'), ('inactive', 'inactive')], default='active', max_length=20)),
                ('type', models.CharField(choices=[('actif', 'Actif'), ('passif', 'Passif')], default='actif', max_length=20)),
                ('date_install', models.DateField()),
                ('date_dernier_serveillance', models.DateField(blank=True, null=True)),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rfid_captures', to='sites.site')),
            ],
        ),
        migrations.CreateModel(
            name='SiteParametre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valeur', models.FloatField()),
                ('date_heure', models.DateTimeField()),
                ('typeParametre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='valeurs', to='captures.typeparametre')),
            ],
        ),
        migrations.CreateModel(
            name='PathTemplatePoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordre', models.IntegerField()),
                ('point', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='captures.trackingpoint')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='captures.pathtemplate')),
            ],
        ),
        migrations.CreateModel(
            name='ObjectTracking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categorie', models.CharField(max_length=50)),
                ('etat', models.CharField(max_length=20)),
                ('capture_RFID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='captures.tagrfid')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sites.site')),
            ],
        ),
        migrations.CreateModel(
            name='MesseurTracking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_debut', models.DateField()),
                ('date_fin', models.DateField()),
                ('date_prevu', models.DateField()),
                ('lieu', models.CharField(max_length=255)),
                ('heure', models.TimeField()),
                ('duree_passage', models.TimeField()),
                ('capture_rfid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='captures.tagrfid')),
                ('object_tracking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='captures.objecttracking')),
                ('path', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='captures.pathtemplate')),
            ],
            options={
                'unique_together': {('capture_rfid', 'path')},
            },
        ),
    ]
