# Generated by Django 5.0.2 on 2025-08-11 14:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('captures', '0001_initial'),
        ('sites', '0002_alter_site_etat'),
    ]

    operations = [
        migrations.CreateModel(
            name='PathTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('source', models.CharField(max_length=100)),
                ('destination', models.CharField(max_length=100)),
                ('latitude_src', models.FloatField()),
                ('longitude_src', models.FloatField()),
                ('latitude_dest', models.FloatField()),
                ('longitude_dest', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='TrackingPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_lieu', models.CharField(max_length=100)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
            ],
        ),
        migrations.RemoveField(
            model_name='objecttracking',
            name='capture_rfid',
        ),
        migrations.RemoveField(
            model_name='mesuretracking',
            name='object_tracking',
        ),
        migrations.RemoveField(
            model_name='objecttracking',
            name='dernier_update',
        ),
        migrations.RemoveField(
            model_name='objecttracking',
            name='latitude_actuel',
        ),
        migrations.RemoveField(
            model_name='objecttracking',
            name='latitude_depart',
        ),
        migrations.RemoveField(
            model_name='objecttracking',
            name='latitude_dest',
        ),
        migrations.RemoveField(
            model_name='objecttracking',
            name='longitude_actuel',
        ),
        migrations.RemoveField(
            model_name='objecttracking',
            name='longitude_depart',
        ),
        migrations.RemoveField(
            model_name='objecttracking',
            name='longitude_dest',
        ),
        migrations.RemoveField(
            model_name='siteparametre',
            name='capture',
        ),
        migrations.RemoveField(
            model_name='siteparametre',
            name='parametre',
        ),
        migrations.AddField(
            model_name='siteparametre',
            name='typeParametre',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='valeurs', to='captures.typeparametre'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='typeparametre',
            name='capture',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='parametres', to='captures.capturesite'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='typeparametre',
            name='site',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='parametre', to='sites.site'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='capturesite',
            name='status',
            field=models.CharField(choices=[('active', 'active'), ('inactive', 'inactive')], default='active', max_length=20),
        ),
        migrations.AlterField(
            model_name='objecttracking',
            name='site',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sites.site'),
        ),
        migrations.CreateModel(
            name='TagRfid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_serie', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('actif', 'Actif'), ('passif', 'Passif')], default='actif', max_length=20)),
                ('type', models.CharField(max_length=20)),
                ('date_install', models.DateField()),
                ('date_dernier_serveillance', models.DateField()),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rfid_captures', to='sites.site')),
            ],
        ),
        migrations.CreateModel(
            name='MesseurTracking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_debut', models.DateField()),
                ('date_fin', models.DateField()),
                ('date_prevu', models.DateField()),
                ('lieu', models.CharField(max_length=255)),
                ('heure', models.TimeField()),
                ('duree_passage', models.TimeField()),
                ('object_tracking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='captures.objecttracking')),
                ('path', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='captures.pathtemplate')),
                ('capture_rfid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='captures.tagrfid')),
            ],
            options={
                'unique_together': {('capture_rfid', 'path')},
            },
        ),
        migrations.CreateModel(
            name='PathTemplatePoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordre', models.IntegerField()),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='captures.pathtemplate')),
                ('point', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='captures.trackingpoint')),
            ],
        ),
        migrations.DeleteModel(
            name='CaptureRFID',
        ),
        migrations.AddField(
            model_name='objecttracking',
            name='capture_RFID',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='captures.tagrfid'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='MesureTracking',
        ),
    ]
