# Generated by Django 4.2.23 on 2025-08-17 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('captures', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pathtemplatepoint',
            name='date_prevu',
            field=models.DateField(blank=True, help_text='Date prévue de passage à ce point', null=True),
        ),
        migrations.AlterField(
            model_name='messeurtracking',
            name='date_prevu',
            field=models.DateField(help_text='Date prévue pour la position actuelle'),
        ),
        migrations.AlterField(
            model_name='messeurtracking',
            name='lieu',
            field=models.CharField(help_text="Lieu actuel de l'objet", max_length=255),
        ),
    ]
