# Generated by Django 4.2.23 on 2025-08-11 15:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0002_alter_site_etat'),
        ('captures', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='siteparametre',
            name='capture',
        ),
        migrations.RemoveField(
            model_name='siteparametre',
            name='parametre',
        ),
        migrations.AddField(
            model_name='siteparametre',
            name='typeParametre',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='valeurs', to='captures.typeparametre'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='typeparametre',
            name='capture',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='parametres', to='captures.capturesite'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='typeparametre',
            name='site',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='parametre', to='sites.site'),
            preserve_default=False,
        ),
    ]
