# Generated by Django 5.0.2 on 2025-08-04 18:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('captures', '0001_initial'),
        ('sites', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='objecttracking',
            old_name='etat',
            new_name='status',
        ),
        migrations.AlterField(
            model_name='capturesite',
            name='status',
            field=models.CharField(choices=[('active', 'active'), ('inactive', 'inactive')], default='active', max_length=20),
        ),
        migrations.CreateModel(
            name='TagRfid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_serie', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('actif', 'Actif'), ('passif', 'Passif')], default='actif', max_length=20)),
                ('type', models.CharField(max_length=20)),
                ('date_install', models.DateField()),
                ('date_dernier_serveillance', models.DateField()),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rfid_captures', to='sites.site')),
            ],
        ),
        migrations.AlterField(
            model_name='objecttracking',
            name='capture_rfid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='object_trackings', to='captures.tagrfid'),
        ),
        migrations.DeleteModel(
            name='CaptureRFID',
        ),
    ]
