# Generated by Django 4.2.23 on 2025-08-18 15:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('captures', '0002_add_date_prevu_to_pathtemplate'),
    ]

    operations = [
        migrations.CreateModel(
            name='PositionHistorique',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lieu', models.CharField(help_text='Nom du lieu', max_length=255)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('timestamp', models.DateTimeField(help_text='Timestamp de la position')),
                ('duree_dans_lieu', models.DurationField(blank=True, help_text='Durée totale passée dans ce lieu', null=True)),
                ('date_entree', models.DateTimeField(blank=True, help_text="Date/heure d'entrée dans ce lieu", null=True)),
                ('date_sortie', models.DateTimeField(blank=True, help_text='Date/heure de sortie de ce lieu', null=True)),
                ('messeur_tracking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='positions_historique', to='captures.messeurtracking')),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['messeur_tracking', '-timestamp'], name='captures_po_messeur_4b9f68_idx'), models.Index(fields=['lieu', '-timestamp'], name='captures_po_lieu_00a9e2_idx')],
            },
        ),
    ]
