# Generated by Django 5.0.2 on 2025-08-08 18:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('captures', '0002_rename_etat_objecttracking_status_and_more'),
        ('sites', '0002_alter_site_etat'),
    ]

    operations = [
        migrations.CreateModel(
            name='PathTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('source', models.CharField(max_length=100)),
                ('destination', models.CharField(max_length=100)),
                ('latitude_src', models.FloatField()),
                ('longitude_src', models.FloatField()),
                ('latitude_dest', models.FloatField()),
                ('longitude_dest', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='TrackingPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_lieu', models.CharField(max_length=100)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
            ],
        ),
        migrations.RenameField(
            model_name='objecttracking',
            old_name='status',
            new_name='etat',
        ),
        migrations.RemoveField(
            model_name='objecttracking',
            name='capture_rfid',
        ),
        migrations.RemoveField(
            model_name='objecttracking',
            name='dernier_update',
        ),
        migrations.RemoveField(
            model_name='objecttracking',
            name='latitude_actuel',
        ),
        migrations.RemoveField(
            model_name='objecttracking',
            name='latitude_depart',
        ),
        migrations.RemoveField(
            model_name='objecttracking',
            name='latitude_dest',
        ),
        migrations.RemoveField(
            model_name='objecttracking',
            name='longitude_actuel',
        ),
        migrations.RemoveField(
            model_name='objecttracking',
            name='longitude_depart',
        ),
        migrations.RemoveField(
            model_name='objecttracking',
            name='longitude_dest',
        ),
        migrations.AlterField(
            model_name='objecttracking',
            name='site',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sites.site'),
        ),
        migrations.CreateModel(
            name='MesseurTracking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_debut', models.DateField()),
                ('date_fin', models.DateField()),
                ('date_prevu', models.DateField()),
                ('lieu', models.CharField(max_length=255)),
                ('heure', models.TimeField()),
                ('duree_passage', models.TimeField()),
                ('capture_rfid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='captures.tagrfid')),
                ('object_tracking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='captures.objecttracking')),
                ('path', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='captures.pathtemplate')),
            ],
            options={
                'unique_together': {('capture_rfid', 'path')},
            },
        ),
        migrations.CreateModel(
            name='PathTemplatePoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordre', models.IntegerField()),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='captures.pathtemplate')),
                ('point', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='captures.trackingpoint')),
            ],
        ),
        migrations.DeleteModel(
            name='MesureTracking',
        ),
        migrations.AddField(
            model_name='objecttracking',
            name='capture_RFID',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='captures.tagrfid'),
            preserve_default=False,
        ),
    ]
