# Generated by Django 4.2.23 on 2025-08-14 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('captures', '0002_pathtemplate_trackingpoint_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tagrfid',
            name='date_dernier_serveillance',
            field=models.DateField(blank=True, null=True),
        ),
    ]
