# Generated by Django 4.2.23 on 2025-08-14 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('captures', '0003_alter_tagrfid_date_dernier_serveillance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tagrfid',
            name='status',
            field=models.CharField(choices=[('active', 'active'), ('inactive', 'inactive')], default='active', max_length=20),
        ),
        migrations.AlterField(
            model_name='tagrfid',
            name='type',
            field=models.CharField(choices=[('actif', 'Actif'), ('passif', 'Passif')], default='actif', max_length=20),
        ),
    ]
