# Generated by Django 5.0.2 on 2025-08-08 20:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('captures', '0003_pathtemplate_trackingpoint_and_more'),
        ('sites', '0002_alter_site_etat'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteparametre',
            name='site',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='parametre', to='sites.site'),
            preserve_default=False,
        ),
    ]
