# Generated by Django 4.2.23 on 2025-08-14 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('captures', '0004_alter_tagrfid_status_alter_tagrfid_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tagrfid',
            name='num_serie',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
