# Generated by Django 5.0.2 on 2025-08-08 23:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('captures', '0004_siteparametre_site'),
        ('sites', '0002_alter_site_etat'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='siteparametre',
            name='capture',
        ),
        migrations.RemoveField(
            model_name='siteparametre',
            name='parametre',
        ),
        migrations.RemoveField(
            model_name='siteparametre',
            name='site',
        ),
        migrations.AddField(
            model_name='siteparametre',
            name='typeParametre',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='valeurs', to='captures.typeparametre'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='typeparametre',
            name='capture',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='parametres', to='captures.capturesite'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='typeparametre',
            name='site',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='parametre', to='sites.site'),
            preserve_default=False,
        ),
    ]
