# Generated by Django 4.2.23 on 2025-08-14 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('captures', '0005_alter_tagrfid_num_serie'),
    ]

    operations = [
        migrations.AlterField(
            model_name='capturesite',
            name='date_dernier_serveillance',
            field=models.DateField(blank=True, null=True),
        ),
    ]
