###
    POST http://127.0.0.1:8000/api/tenants/add-client/ HTTP/1.1
    Content-Type:application/json 

    {
        "email": "mr_maamar+2@esi.dz",
        "password": "123456",
        "telephone": "0551234567",
        "nom_entreprise": "mira",
        "role" :"client",
        "adresse": "Baraki, Alger, Algérie",
        "latitude": "36.7538",
        "longitude": "3.0588",
        "industrie": "Construction",
        "nom_resp": "Rofa",
        "prenom_resp": "Mmr",
        "status": "active" 
    }

