#login endpoint

    POST http://127.0.0.1:8000/api/user/token/ HTTP/1.1
    Content-Type: application/json
    
    {
        "email" : "mr_maamar@esi.dz",
        "password" :"@123456@maamar"
    }

###
    POST http://127.0.0.1:8000/api/user/token/refresh/ HTTP/1.1
    Content-Type: application/json 

    { 
        "refresh" : "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoicmVmcmVzaCIsImV4cCI6MTc1NDQ0MTkxNCwiaWF0IjoxNzU0MzU1NTE0LCJqdGkiOiI3YzU0YzJlNzE1N2Q0ZjM1YTZjNGFiMTM0ZjI2MjYyNyIsInVzZXJfaWQiOjF9.kf--4iGUCq_fA_C88iG6j-LcAA8ZhVVRPR7WZmqVkuM"
    }

### 
    PUT  http://127.0.0.1:8000/api/user/change-password/ HTTP/1.1
    Content-Type:application/json 
    Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzU0MzcwMzg2LCJpYXQiOjE3NTQzNzAwODYsImp0aSI6IjhlZTc5NzU5MzU4MTRjM2M5M2MyZTIxNTI2ODY2Yzk1IiwidXNlcl9pZCI6MX0.H1my-TFuNBMaU22V9RrgwCa2MVU-XdJozHbOqf-gRWE

    {
        "old_password":"123456" ,
        "new_password":"1234567"

    }


###
    POST  http://127.0.0.1:8000/api/user/password-reset/ HTTP/1.1
    Content-Type:application/json 
   # Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzU0MzcwMzg2LCJpYXQiOjE3NTQzNzAwODYsImp0aSI6IjhlZTc5NzU5MzU4MTRjM2M5M2MyZTIxNTI2ODY2Yzk1IiwidXNlcl9pZCI6MX0.H1my-TFuNBMaU22V9RrgwCa2MVU-XdJozHbOqf-gRWE

    {
        "email" : "mr_maamar@esi.dz"
    }


### 
    POST http://127.0.0.1:8000/api/user/password-reset/confirm/ HTTP/1.1
    Content-Type:application/json 
    Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzU0MzcwMzg2LCJpYXQiOjE3NTQzNzAwODYsImp0aSI6IjhlZTc5NzU5MzU4MTRjM2M5M2MyZTIxNTI2ODY2Yzk1IiwidXNlcl9pZCI6MX0.H1my-TFuNBMaU22V9RrgwCa2MVU-XdJozHbOqf-gRWE

    {
        "token": "8940d98ef50e0688413757586d5" ,
        "password": "@123456@maamar"
    }

###
    GET http://127.0.0.1:8000/api/tenants/clients/ HTTP/1.1
    Content-Type:application/json
    
###
    GET http://nomentrprise.localhost:8000/api/tenants/clients/1/ HTTP/1.1

###
# TTN7A hadi 
    POST http://nomentrprise.localhost:8000/api/site/add-site/ HTTP/1.1
    Content-Type:application/json 

    { 
        "nom" :"Site2",
        "adresse":"Baraki - Alger" , 
        "latitude":"5" ,
        "longitude" :"6",
        "asset_tracking":0
    }



###
    POST http://nomentrprise.localhost:8000/api/site/add-site/ HTTP/1.1
    Content-Type:application/json 

    
        {
            "nom": "Site A",
            "adresse": "123 Main St",
            "latitude": 36.75,
            "longitude": 3.04,
            "asset_tracking": true,
            "parametre": [
                {
                    "nom": "temperateur",
                    "unite": "Celsius",
                    "valeur_max": 100,
                    "capture": {
                        "num_serie": "Capture5",
                        "date_install": "2025-08-09",
                        "date_dernier_serveillance": "2025-08-10"
                    }
                },
                {
                    "nom": "humidite",
                    "unite": "%",
                    "valeur_max": 80,
                    "capture": {
                        "num_serie": "Capture6",
                        "date_install": "2025-08-09",
                        "date_dernier_serveillance": "2025-08-10"
                    }
                }
            ]
        }

    
