#login endpoint

    POST http://127.0.0.1:8000/api/user/token/ HTTP/1.1
    Content-Type: application/json
    
    {
        "email" : "client@example.com",
        "password": "SecurePassword123"
      
    }

###
    POST http://127.0.0.1:8000/api/user/token/refresh/ HTTP/1.1
    Content-Type: application/json 

    { 
        "refresh" : "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoicmVmcmVzaCIsImV4cCI6MTc1NDQ0MTkxNCwiaWF0IjoxNzU0MzU1NTE0LCJqdGkiOiI3YzU0YzJlNzE1N2Q0ZjM1YTZjNGFiMTM0ZjI2MjYyNyIsInVzZXJfaWQiOjF9.kf--4iGUCq_fA_C88iG6j-LcAA8ZhVVRPR7WZmqVkuM"
    }

### 
    PUT  http://127.0.0.1:8000/api/user/change-password/ HTTP/1.1
    Content-Type:application/json 
    Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzU0MzcwMzg2LCJpYXQiOjE3NTQzNzAwODYsImp0aSI6IjhlZTc5NzU5MzU4MTRjM2M5M2MyZTIxNTI2ODY2Yzk1IiwidXNlcl9pZCI6MX0.H1my-TFuNBMaU22V9RrgwCa2MVU-XdJozHbOqf-gRWE

    {
        "old_password":"123456" ,
        "new_password":"1234567"

    }


###
    POST  http://127.0.0.1:8000/api/user/password-reset/ HTTP/1.1
    Content-Type:application/json 
   # Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzU0MzcwMzg2LCJpYXQiOjE3NTQzNzAwODYsImp0aSI6IjhlZTc5NzU5MzU4MTRjM2M5M2MyZTIxNTI2ODY2Yzk1IiwidXNlcl9pZCI6MX0.H1my-TFuNBMaU22V9RrgwCa2MVU-XdJozHbOqf-gRWE

    {
        "email" : "mr_maamar@esi.dz"
    }


### 
    POST http://127.0.0.1:8000/api/user/password-reset/confirm/ HTTP/1.1
    Content-Type:application/json 
    Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzU0MzcwMzg2LCJpYXQiOjE3NTQzNzAwODYsImp0aSI6IjhlZTc5NzU5MzU4MTRjM2M5M2MyZTIxNTI2ODY2Yzk1IiwidXNlcl9pZCI6MX0.H1my-TFuNBMaU22V9RrgwCa2MVU-XdJozHbOqf-gRWE

    {
        "token": "9e4bd7548e485f1f22f1c05cf2bb3916" ,
        "password": "@1234567@maamar"
    }

###
    GET http://127.0.0.1:8000/api/tenants/clients/ HTTP/1.1
    Content-Type:application/json
    
###
    GET http://nomentrprise.localhost:8000/api/tenants/clients/1/ HTTP/1.1

###


###
    POST http://127.0.0.1:8000/api/tenants/add-client/ HTTP/1.1
    Content-Type:application/json 

    {
        "email": "client@example.com",
        "password": "SecurePassword123",
        "telephone": "0551234567",
        "nom_entreprise": "nomentrprise",
        "adresse": "Rue 12, Alger, Algérie",
        "latitude": "36.7538",
        "longitude": "3.0588",
        "industrie": "Construction",
        "nom_resp": "Ahmed",
        "prenom_resp": "Ali",
        "status": "active" 
    }


###
    POST http://nomentrprise.localhost:8000/api/site/add-site/ HTTP/1.1
    Content-Type:application/json 

    
        {
            "nom": "Site B",
            "adresse": "123 Main St",
            "latitude": 36.75,
            "longitude": 3.04,
            "asset_tracking": true,
            "parametre": [
                {
                    "nom": "temperateur",
                    "unite": "Celsius",
                    "valeur_max": 100,
                    "capture": {
                        "num_serie": "Capture8",
                        "date_install": "2025-08-09",
                        "date_dernier_serveillance": "2025-08-10"
                    }
                },
                {
                    "nom": "humidite",
                    "unite": "%",
                    "valeur_max": 80,
                    "capture": {
                        "num_serie": "Capture9",
                        "date_install": "2025-08-09",
                        "date_dernier_serveillance": "2025-08-10"
                    }
                }
            ]
        }

    




###
    POST http://nomentrprise.localhost:8000/api/machine/add-machine/ HTTP/1.1
    Content-Type:application/json 

    {
    "site": 1,
    "identificateur": "M-123",
    "status": "active",
    "date_installation": "2025-08-13T10:00:00Z",
    "captures": [
        {
            "num_serie": "C-001",
            "date_install": "2025-08-13",
            "parametres": [
                {"nom": "temperature", "unite": "°C", "valeur_max": 100},
                {"nom": "voltage", "unite": "v", "valeur_max": 10}
            ]
        },
        {
            "num_serie": "C-002",
            "date_install": "2025-08-13",
            "parametres": [
                {"nom": "humidite", "unite": "%", "valeur_max": 80}
            ]
        },
        {
            "num_serie": "C-003",
            "date_install": "2025-08-13",
            "parametres": [
                {"nom": "vibration", "unite": "Hz", "valeur_max": 500}
            ]
        }
    ]
}



###
    POST http://nomentrprise.localhost:8000/api/clientUsers/add-clientuser/ HTTP/1.1
    Content-Type:application/json 

    {
        
        "email": "clientuser6@example.com",
        "password": "123456",
        "telephone": "+213123456789",
        "role": "canread"

    }

###
  POST http://nomentrprise.localhost:8000/api/clientUsers/upload-clientuser/ HTTP/1.1
    Content-Type: multipart/form-data

    file: ./Book1.xlsx


#curl -X POST "http://127.0.0.1:8000/api/ClientUsers/upload-clientuser/" -F "file=@Book1.xlsx"

###
    POST http://nomentrprise.localhost:8000/api/captures/add-tag-rfid/ HTTP/1.1
    Content-Type:application/json 
    
    {
    "site" : 1,
    "num_serie": "RFID123456",
    "type": "actif",
    "date_install": "2025-08-14"
    }




curl -X POST "http://nomentrprise.localhost:8000/api/captures/upload-tag-rfid/" \ -F "file=@test_tags.xlsx" \ -F "site=1"
