#login endpoint

    POST http://127.0.0.1:8000/api/user/token/ HTTP/1.1
    Content-Type: application/json
    
    {
        "email" : "mr_maamar+2@esi.dz",
        "password": "123456"
      
    }

###
    POST http://127.0.0.1:8000/api/user/token/refresh/ HTTP/1.1
    Content-Type: application/json 

    { 
        "refresh" : "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoicmVmcmVzaCIsImV4cCI6MTc1NDQ0MTkxNCwiaWF0IjoxNzU0MzU1NTE0LCJqdGkiOiI3YzU0YzJlNzE1N2Q0ZjM1YTZjNGFiMTM0ZjI2MjYyNyIsInVzZXJfaWQiOjF9.kf--4iGUCq_fA_C88iG6j-LcAA8ZhVVRPR7WZmqVkuM"
    }

### 
    PUT  http://127.0.0.1:8000/api/user/change-password/ HTTP/1.1
    Content-Type:application/json 
    Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzU0MzcwMzg2LCJpYXQiOjE3NTQzNzAwODYsImp0aSI6IjhlZTc5NzU5MzU4MTRjM2M5M2MyZTIxNTI2ODY2Yzk1IiwidXNlcl9pZCI6MX0.H1my-TFuNBMaU22V9RrgwCa2MVU-XdJozHbOqf-gRWE

    {
        "old_password":"123456" ,
        "new_password":"1234567"

    }


###
    POST  http://127.0.0.1:8000/api/user/password-reset/ HTTP/1.1
    Content-Type:application/json 
   # Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzU0MzcwMzg2LCJpYXQiOjE3NTQzNzAwODYsImp0aSI6IjhlZTc5NzU5MzU4MTRjM2M5M2MyZTIxNTI2ODY2Yzk1IiwidXNlcl9pZCI6MX0.H1my-TFuNBMaU22V9RrgwCa2MVU-XdJozHbOqf-gRWE

    {
        "email" : "mr_maamar@esi.dz"
    }


### 
    POST http://127.0.0.1:8000/api/user/password-reset/confirm/ HTTP/1.1
    Content-Type:application/json 
    Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzU0MzcwMzg2LCJpYXQiOjE3NTQzNzAwODYsImp0aSI6IjhlZTc5NzU5MzU4MTRjM2M5M2MyZTIxNTI2ODY2Yzk1IiwidXNlcl9pZCI6MX0.H1my-TFuNBMaU22V9RrgwCa2MVU-XdJozHbOqf-gRWE

    {
        "token": "9e4bd7548e485f1f22f1c05cf2bb3916" ,
        "password": "@1234567@maamar"
    }

###
    GET http://127.0.0.1:8000/api/tenants/clients/ HTTP/1.1
    Content-Type:application/json
    



  #   i should start correcting from this one 
###
    GET http://127.0.0.1:8000/api/tenants/clients/4/ HTTP/1.1

###



    




###


###
  POST http://nomentrprise.localhost:8000/api/clientUsers/upload-clientuser/ HTTP/1.1
    Content-Type: multipart/form-data

    file: ./Book1.xlsx


#curl -X POST "http://127.0.0.1:8000/api/ClientUsers/upload-clientuser/" -F "file=@Book1.xlsx"

###
    POST http://127.0.0.1:8000/api/captures/add-tag-rfid/?client_id=2 HTTP/1.1
    Content-Type:application/json 
    
    {
        "site" : 1,
        "num_serie": "Az",
        "type": "actif",
        "date_install": "2025-08-14"
    }




#curl -X POST "http://127.0.0.1:8000/api/captures/upload-tag-rfid/?client_id=2" \ -F "file=@tagrfid1.xlsx" \ -F "site=1"


#consulter detail de client -> voir le detail de site de client 
###
GEt http://127.0.0.1:8000/api/site/sites/?client_id=1&site_id=1 HTTP/1.1





### 2 is the site id , 2 is the client id 
PATCH  http://127.0.0.1:8000/api/site/update-site/2/?client_id=2  
Content-Type: application/json


{
  "adresse": "42 Rue de Paris"
}

### 

GET  http://127.0.0.1:8000/api/machine/machines/?client_id=2&machine_id=2





###

GET http://127.0.0.1:8000/api/site/captures-site/2/?client_id=2   



###

GET http://127.0.0.1:8000/api/clientUsers/list-clientuser/?client_id=1&site_id=2



