#consulter detail de client -> voir le detail de site de client 
###
GEt http://127.0.0.1:8000/api/site/sites/?client_id=1&site_id=1 HTTP/1.1





### 2 is the site id , 2 is the client id 
PATCH  http://127.0.0.1:8000/api/site/update-site/2/?client_id=2  
Content-Type: application/json


{
  "adresse": "42 Rue de Paris"
}