# Generated by Django 4.2.23 on 2025-08-14 03:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0002_alter_site_etat'),
        ('ClientUsers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientuser',
            name='site_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='sites.site'),
        ),
    ]
