# Generated by Django 4.2.23 on 2025-08-16 17:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ClientUsers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FichierTicket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='FichierTicketReponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='ResponseTicket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=50)),
                ('urgence', models.CharField(max_length=20)),
                ('objet', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('status', models.CharField(max_length=20)),
                ('client_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ClientUsers.clientuser')),
            ],
        ),
    ]
