# Generated by Django 4.2.23 on 2025-08-03 19:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_admin_clientuser_alter_user_logged_in_and_more'),
        ('tickets', '0003_fichierticket_fichierticketreponse_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='responseticket',
            name='sender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.admin'),
        ),
        migrations.AlterField(
            model_name='responseticket',
            name='ticket',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tickets.ticket'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='client_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.clientuser'),
        ),
        migrations.DeleteModel(
            name='TicketFile',
        ),
        migrations.AddField(
            model_name='fichierticketreponse',
            name='response_ticket',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tickets.responseticket'),
        ),
        migrations.AddField(
            model_name='fichierticket',
            name='ticket',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tickets.ticket'),
        ),
    ]
