# Generated by Django 5.0.2 on 2025-08-04 18:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ClientUsers', '0001_initial'),
        ('tickets', '0004_alter_responseticket_sender_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ticket',
            old_name='etat',
            new_name='status',
        ),
        migrations.AlterField(
            model_name='ticket',
            name='client_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ClientUsers.clientuser'),
        ),
    ]
