# Generated by Django 4.2.23 on 2025-08-16 17:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ClientUsers', '0001_initial'),
        ('machines', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FichierMaintenanceAdmin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='FichierMaintenanceClient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='MaintenanceAdmin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_intervention', models.DateField()),
                ('type', models.CharField(max_length=50)),
                ('resume', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='MaintenanceAdminPredictive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_intervention', models.DateField()),
                ('detail', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='MaintenanceClientPredictive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_intervention', models.DateField()),
                ('detail', models.TextField()),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ClientUsers.clientuser')),
                ('machine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='machines.machine')),
            ],
        ),
        migrations.CreateModel(
            name='MaintenanceClient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_intervention', models.DateField()),
                ('type', models.CharField(max_length=50)),
                ('resume', models.TextField()),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ClientUsers.clientuser')),
                ('machine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='machines.machine')),
            ],
        ),
    ]
