# Generated by Django 5.0.2 on 2025-08-08 18:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ClientUsers', '0001_initial'),
        ('maintenance', '0001_initial'),
        ('users', '0004_alter_user_managers'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='maintenancesensor',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='maintenancesensor',
            name='machine',
        ),
        migrations.RemoveField(
            model_name='maintenancesensor',
            name='maintenance',
        ),
        migrations.RemoveField(
            model_name='maintenanceclient',
            name='file',
        ),
        migrations.AddField(
            model_name='maintenanceadmin',
            name='admin',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='maintenance_maintenanceprd_admins', to='users.admin'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='maintenanceadminpredictive',
            name='admin',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='users.admin'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='maintenanceclient',
            name='client',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='ClientUsers.clientuser'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='maintenanceclientpredictive',
            name='client',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='ClientUsers.clientuser'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='FichierMaintenanceAdmin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=255)),
                ('maintenance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='maintenance.maintenanceadmin')),
            ],
        ),
        migrations.CreateModel(
            name='FichierMaintenanceClient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=255)),
                ('maintenance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='maintenance.maintenanceclient')),
            ],
        ),
        migrations.DeleteModel(
            name='Attachment',
        ),
        migrations.DeleteModel(
            name='MaintenanceSensor',
        ),
    ]
