# Generated by Django 4.2.23 on 2025-08-16 17:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('maintenance', '0001_initial'),
        ('users', '0001_initial'),
        ('machines', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='maintenanceadminpredictive',
            name='admin',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.admin'),
        ),
        migrations.AddField(
            model_name='maintenanceadminpredictive',
            name='capture_machine',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='machines.capturemachine'),
        ),
        migrations.AddField(
            model_name='maintenanceadmin',
            name='admin',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maintenance_maintenanceprd_admins', to='users.admin'),
        ),
        migrations.AddField(
            model_name='maintenanceadmin',
            name='capture_machine',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='machines.capturemachine'),
        ),
        migrations.AddField(
            model_name='fichiermaintenanceclient',
            name='maintenance',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='maintenance.maintenanceclient'),
        ),
        migrations.AddField(
            model_name='fichiermaintenanceadmin',
            name='maintenance',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='maintenance.maintenanceadmin'),
        ),
    ]
