# Generated by Django 4.2.23 on 2025-08-02 03:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sites', '0001_initial'),
        ('captures', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CaptureMachine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_serie', models.CharField(max_length=100, unique=True)),
                ('status', models.CharField(max_length=20)),
                ('date_install', models.DateField()),
                ('date_dernier_serveillance', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='MachineParametre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valeur', models.FloatField()),
                ('date_heure', models.DateTimeField()),
                ('capture_machine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parametres', to='machines.capturemachine')),
                ('parametre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='captures.typeparametre')),
            ],
        ),
        migrations.CreateModel(
            name='Machine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identificateur', models.CharField(max_length=100)),
                ('etat', models.CharField(max_length=20)),
                ('date_installation', models.DateTimeField()),
                ('date_dernier_serv', models.DateTimeField()),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='machines', to='sites.site')),
            ],
        ),
        migrations.AddField(
            model_name='capturemachine',
            name='machine',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='captures', to='machines.machine'),
        ),
    ]
