# Generated by Django 4.2.23 on 2025-08-16 17:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sites', '0002_alter_site_etat'),
    ]

    operations = [
        migrations.CreateModel(
            name='CaptureMachine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_serie', models.CharField(max_length=100, unique=True)),
                ('status', models.CharField(choices=[('active', 'active'), ('inactive', 'inactive')], default='active', max_length=20)),
                ('date_install', models.DateField()),
                ('date_dernier_serveillance', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Parametre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50)),
                ('unite', models.CharField(max_length=20)),
                ('valeur_max', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('captureMachine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parametre', to='machines.capturemachine')),
            ],
        ),
        migrations.CreateModel(
            name='MachineParametre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valeur', models.FloatField()),
                ('date_heure', models.DateTimeField()),
                ('parametre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='machines.parametre')),
            ],
        ),
        migrations.CreateModel(
            name='Machine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identificateur', models.CharField(max_length=100, unique=True)),
                ('status', models.CharField(choices=[('active', 'active'), ('inactive', 'inactive')], default='active', max_length=20)),
                ('date_dernier_serv', models.DateTimeField(blank=True, null=True)),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='machines', to='sites.site')),
            ],
        ),
        migrations.AddField(
            model_name='capturemachine',
            name='machine',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='captures', to='machines.machine'),
        ),
    ]
