# Generated by Django 4.2.23 on 2025-08-13 11:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('machines', '0002_remove_machine_etat_machine_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='machine',
            name='date_installation',
        ),
        migrations.RemoveField(
            model_name='machineparametre',
            name='capture_machine',
        ),
        migrations.CreateModel(
            name='Parametre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50)),
                ('unite', models.CharField(max_length=20)),
                ('valeur_max', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('captureMachine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parametre', to='machines.capturemachine')),
            ],
        ),
        migrations.AlterField(
            model_name='machineparametre',
            name='parametre',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='machines.parametre'),
        ),
    ]
