# Generated by Django 4.2.23 on 2025-08-13 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('machines', '0003_remove_machine_date_installation_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='machine',
            name='date_dernier_serv',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
