# Generated by Django 4.2.23 on 2025-08-13 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('machines', '0004_alter_machine_date_dernier_serv'),
    ]

    operations = [
        migrations.AlterField(
            model_name='capturemachine',
            name='date_dernier_serveillance',
            field=models.DateField(blank=True, null=True),
        ),
    ]
