# Generated by Django 4.2.23 on 2025-08-08 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Site',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('adresse', models.CharField(blank=True, max_length=255, null=True)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('asset_tracking', models.BooleanField(default=False)),
                ('etat', models.CharField(max_length=20)),
                ('date_ajout', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
