# Generated by Django 5.0.2 on 2025-08-04 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0005_rename_etat_ticket_status_alter_ticket_client_user'),
        ('users', '0002_admin_clientuser_alter_user_logged_in_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='username',
        ),
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'admin'), ('Client', 'client'), ('userClient', 'userClient')], default='admin', max_length=20),
        ),
        migrations.AlterField(
            model_name='admin',
            name='status',
            field=models.CharField(blank=True, choices=[('active', 'active'), ('inactive', 'inactive')], default='active', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.DeleteModel(
            name='ClientUser',
        ),
    ]
